### ISSUE TITLE
Add support for new arguments (tag_separator, etc)

### ISSUE THREAD

**Issue by ayavilevich** [cliffano/eggtart#4]
Hi,

Looks like some new arguments were added.
Specifically, see "tag_separator" at https://github.com/SciDevs/delicious-api/blob/master/api/posts.md 

Thanks,
Arik.

**Comment by cliffano** [comment]
I've published eggtart v0.1.1 with tag_separator arg support to /v1/posts/get and /v1/posts/all .

Thanks for raising this issue, I haven't been closely following Delicious API updates, in fact I missed the news on last year's Delicious sale to ScienceInc.

Please feel free to let me know if there's any other issue.

**Comment by ayavilevich** [comment]
Thanks!
