### ISSUE TITLE
Is the 'https://api.del.icio.us/v1/*' API working for you?

### ISSUE THREAD

**Issue by emeraldjava** [cliffano/eggtart#5]
Hi,
Just wondering is the del.icio.us API still working for you? I've a similar java client but it seems the API has been retired.
Thanks,
Paul

**Comment by cliffano** [comment]
@emeraldjava Yep, it has been responding with server error for a while.
There was a slight glitch when Delicious was sold to Avos, but then I noticed that it started having lots of errors when it was sold to Science Inc.
I'm not holding my breath for Delicious to return to its heyday.
